In [1]:
import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("CUDA is available")
    for gpu in gpus:
        print(f"Device: {gpu}")
else:
    print("CUDA is not available")

# Exemple de calcul sur GPU
with tf.device('/GPU:0'):
    x = tf.random.normal([5, 5])
    y = tf.random.normal([5, 5])
    z = x + y

print("x:", x.numpy())
print("y:", y.numpy())
print("z (x + y):", z.numpy())

2025-02-19 16:21:34.982936: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-19 16:21:35.067894: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739978495.108905   23917 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739978495.120448   23917 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-19 16:21:35.211394: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

CUDA is available
Device: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
x: [[ 1.3685795  -1.1767209  -0.40801698  0.27598298 -1.8022623 ]
 [ 0.19491047  1.4662622  -1.2260743  -1.6061565  -0.7815142 ]
 [ 1.4311146   0.6711198  -1.264209   -0.22543913 -0.5455445 ]
 [-1.5637022   0.6300961   0.45531797  1.4470798   1.4498528 ]
 [ 0.36646304  0.31655917  0.50931036 -0.03427306 -0.40696082]]
y: [[-0.23560078  0.19236232 -2.52676    -1.0506045   0.7093081 ]
 [ 0.37546605  0.8237073  -0.08980572 -0.9126245  -2.1416986 ]
 [-0.92179704  0.3099611  -0.2919554   0.36305335  0.31577063]
 [-0.8824928  -0.89732075 -1.5744561   0.00789111  1.2438232 ]
 [-0.02836882 -0.32864964 -0.36644942  0.8576894   0.23579454]]
z (x + y): [[ 1.1329787  -0.98435855 -2.934777   -0.7746215  -1.0929542 ]
 [ 0.5703765   2.2899694  -1.3158801  -2.518781   -2.9232128 ]
 [ 0.5093175   0.9810809  -1.5561645   0.13761422 -0.22977388]
 [-2.4461951  -0.26722467 -1.1191381   1.4549708   2.693676  ]
 [ 0.338

I0000 00:00:1739978498.896366   23917 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4267 MB memory:  -> device: 0, name: NVIDIA RTX A3000 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
